import time
print("\033[5;37;40m Welcome to the HYDRA file database. Please enter the password.\033[0;37;40m\n")
time.sleep(1)
print("")
pwd = input(">>> ")
if pwd == "cgi1417a8":
  print("Loading...14%")
  time.sleep(1)
  print("Loading...51%")
  time.sleep(1)
  print("Loading...99%")
  time.sleep(0.5)
  print("Loading...100%")
  time.sleep(1)
  print("\033[1;32;40m Sucess!! You have logged into the HYDRA database.")
  print("\033[1;32;40m YOU NOW HAVE FULL ACCESS TO THE HYDRA TERMINAL")
  time.sleep(1)
  print("Loading files...")
  time.sleep(2)
  print("Loading...14%")
  time.sleep(1)
  print("Loading...51%")
  time.sleep(1)
  print("Loading...99%")
  time.sleep(0.5)
  print("Loading...100%")
  time.sleep(1)
  print("FILES LOADED")
  time.sleep(1)
  print("\033[1;34;40m Enter your terminal commands.")
  print("Use the command 'search' to search for files.")
  print("")
  print("Use the command 'logout' to logout.")
  print("")
  while True:
    cmd = input(">>> ")
    if cmd == "logout":
      print("\033[1;31;40m Logging out...")
      time.sleep(1)
      print("Loading.")
      time.sleep(1)
      print("Loading..")
      time.sleep(1)
      print("Loading...")
      time.sleep(2)
      print("\033[1;32;40m Sucessfully logged out.")
      exit()
    elif cmd == ("files"):
      print("Opening files...")
      time.sleep(1)
      print("Loading.")
      time.sleep(1)
      print("Loading..")
      time.sleep(1)
      print("Loading...")
      time.sleep(2)
      print("\033[1;32;40m Files sucessfully loaded!!")
      print("Use the command 'search' to search for files.")
    elif cmd == "search":
      print("Finding files..")
      time.sleep(2)
      print("Loading...")
      time.sleep(2)
      print("\033[1;32;40m 1 result(s) found in database.")
      time.sleep(1)
      yn = input("See results? [y,n]: ")
      if yn == "y":
        print("File list:")
        time.sleep(1)
        print("1. Goverment plan.")
        time.sleep(1)
        yn2 = input("Open? [y,n]: ")
        if yn2 == "y":
          print("2783277n28f27f3871#!&%FH$Q*$Q#T*34tn41398tn3q1R##QIFEQ*F$#QTH$EQGTqnt482394t3T#*QGN#QGQ#GQihqt9g8qtGIQ*TQ@NFOQFHA#giogyageGWIAgnagoq348y304y2gq$T*WT$WOYGEHOHsGhrq3gGS[[33Tt3[t0346836[]838693489627btqn89t]]]39502452876792ps@TI$#O(*GREWAHT39tya9te98g")
          time.sleep(1)
          yn3 = input("Un-encrypt? [y,n]: ")
          if yn3 == "y":
            time.sleep(1)
            print("Un-encrypting...")
            time.sleep(1)
            print("Loading.")
            time.sleep(1)
            print("Loading..")
            time.sleep(1)
            print("Loading...")
            time.sleep(2)
            print("\033[1;32;40m File sucessfuly unencrypted!!")
            time.sleep(1)
            print("Reading file...")
            time.sleep(1)
            print("Please wait...")
            time.sleep(3)
            print("The goverment is trying to overtake the world. Operation SPYDER is a seceret missle defense group formed by ISIS to nuke half of the United States. Please take any nessecary precations and prepare wisely for this incoming attack. Signed, The President.")
            print("")
            print("P.S. Aliens may also attack too, so just watch out for that as well.")
        elif yn2 == "n":
          print(" ")
      elif yn == "n":
        print("")
    else:
      print("\033[1;31;40m That command does not exist.")
else:
  print("Loading...14%")
  time.sleep(1)
  print("Loading...51%")
  time.sleep(1)
  print("Loading...99%")
  time.sleep(0.5)
  print("Loading...100%")
  time.sleep(1)
  print("\033[1;31;40m LOGIN FAILED")
  print("\033[1;31;40m You are not authorized. Killing program.")
  time.sleep(2)
  print("\033[1;31;40m ALERT: You have lost full access. No more attempts are allowed.")
  time.sleep(1)
  print("\033[1;31;40m KILLING.")
  time.sleep(1)
  print("\033[1;31;40m KILLING..")
  time.sleep(1)
  print("\033[1;31;40m KILLING...")
  time.sleep(2)
  print(" ")
  exit()